version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-local
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - vault-network
    command: ["vault", "server", "-dev", "-dev-root-token-id=root-token", "-dev-listen-address=0.0.0.0:8200"]

  # Optional: Vault UI helper service
  vault-ui:
    image: nginx:alpine
    container_name: vault-ui-helper
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vault
    restart: unless-stopped
    networks:
      - vault-network

volumes:
  vault-data:
    driver: local

networks:
  vault-network:
    driver: bridge
