---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: k8s-property-secret-poc
  name: vault-static-secret-v2
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: secret/app-secrets/database.host
  version: 2
  refreshAfter: 60s
  destination:
    create: true
    name: static-secret2
